### ISSUE TITLE
有在线体验的地址吗？

### ISSUE THREAD

**Issue by yuanzhiyong1999** [WangRongsheng/CareGPT#1]
想看看整体效果如何

**Comment by WangRongsheng** [comment]
暂时您可以自己部署使用一下。稍后会放出来体验地址。

**Comment by WangRongsheng** [comment]
> 想看看整体效果如何

https://huggingface.co/spaces/wangrongsheng/CareLlama

![image](https://github.com/WangRongsheng/CareLlama/assets/55651568/96f870d1-c028-4ae6-abef-686c839a1e9c)

**Comment by nibaba007** [comment]
演示网站有问题
![image](https://github.com/WangRongsheng/CareGPT/assets/101156432/cb1ab1a0-c7a2-41c8-a6b2-098ff6959169)
