### ISSUE TITLE
有交流沟通群吗，一直运行不成功呢

### ISSUE THREAD

**Issue by futuresnail** [WangRongsheng/CareGPT#11]
您好，有交流沟通群吗，现在运行怎么一直提示错误，
(CareGPT) PS D:\medical\CareGPT> python src/api_demo.py --model_name_or_path ./model/Llama-2-7b-chat-hf --checkpoint_dir output --finetuning_type lora --template
 llama2
C:\ProgramData\anaconda3\envs\CareGPT\Lib\site-packages\transformers\deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be remo
ved in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:54<00:00, 27.15s/it]
C:\ProgramData\anaconda3\envs\CareGPT\Lib\site-packages\transformers\generation\configuration_utils.py:389: UserWarning: `do_sample` is set to `False`. However, 
`temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detect
ed when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
C:\ProgramData\anaconda3\envs\CareGPT\Lib\site-packages\transformers\generation\configuration_utils.py:394: UserWarning: `do_sample` is set to `False`. However, 
`top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when init
ializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
01/08/2024 23:02:47 - INFO - llmtuner.tuner.core.adapter - Fine-tuning method: LoRA
Traceback (most recent call last):
  File "D:\medical\CareGPT\src\api_demo.py", line 14, in <module>
    main()
  File "D:\medical\CareGPT\src\api_demo.py", line 7, in main
    chat_model = ChatModel()
                 ^^^^^^^^^^^
  File "D:\medical\CareGPT\src\llmtuner\chat\stream_chat.py", line 15, in __init__
    self.model, self.tokenizer = load_model_and_tokenizer(model_args, finetuning_args)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\medical\CareGPT\src\llmtuner\tuner\core\loader.py", line 173, in load_model_and_tokenizer
    model = init_adapter(model, model_args, finetuning_args, is_trainable, is_mergeable)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\medical\CareGPT\src\llmtuner\tuner\core\adapter.py", line 63, in init_adapter
    assert os.path.exists(os.path.join(model_args.checkpoint_dir[0], WEIGHTS_NAME)), \
AssertionError: Provided path (output) does not contain a LoRA weight.
(CareGPT) PS D:\medical\CareGPT>

**Comment by WangRongsheng** [comment]
请查看lora权重的路径是否正确。
