### ISSUE TITLE
进行增量预训练一些问题

### ISSUE THREAD

**Issue by EvanSong77** [WangRongsheng/CareGPT#18]
作者大大您好，我想对一个专业领域的数据集进行增量预训练（大约有40w个产品的描述），会增加通用领域的数据（专与通的比例1:7的样子），考虑用ChatGLM3-6b去做，想要学习到领域知识的同时尽可能去避免灾难性遗忘，有些问题想请教一下您：
1.模型是推荐用base还是chat来做增量预训练呢？
2.做完增量预训练后有必要拿通用领域的指令数据集再做一下SFT？
3.我们的显卡资源并不够，只有3块4090，同时数据量也不够，全参微调是做不了，用Lora会不会效果比较差，有没有比较好的建议或者方法？

期待您的回复，祝好！

**Comment by WangRongsheng** [comment]
https://zhuanlan.zhihu.com/p/686642922
