### ISSUE TITLE
项目运行配置

### ISSUE THREAD

**Issue by yuanzhiyong1999** [WangRongsheng/CareGPT#2]
您好，我在线体验了CareLlama，效果很好，想复现一下整个流程，因为我这边训练资源有限，所以想了解一下您当时的训练设备的配置。以及想问问这个模型是根据llama2-7b-chat模型sft得来，为什么不选择中文能力更好的chatglm2呢？期待您的回复，谢谢

**Comment by WangRongsheng** [comment]
> 您好，我在线体验了CareLlama，效果很好，想复现一下整个流程，因为我这边训练资源有限，所以想了解一下您当时的训练设备的配置。以及想问问这个模型是根据llama2-7b-chat模型sft得来，为什么不选择中文能力更好的chatglm2呢？期待您的回复，谢谢

- 目前我训练使用的设备为单卡A100 (40GB)，在其它设备上仍然可以像我一样完成训练，只需要保持足够大的内存和显存以及较小的BS即可。
- 我们尝试过很多开源LLM，如QWen，ChatGLM等，但是一言难尽，我们极力向您推荐LLaMA-2。

**Comment by yuanzhiyong1999** [comment]
> 

非常感谢您的回复，目前在线体验的模型是在llama2-7b-chat上面，利用那么多医学领域数据sft之后的结果吗？还是pretrain、sft和rlhf都做了呢？

**Comment by WangRongsheng** [comment]
当前开源的所有权重仅在llama2-7b-chat上做了sft，并未进行其它训练。

**Comment by yuanzhiyong1999** [comment]
> 当前开源的所有权重仅在llama2-7b-chat上做了sft，并未进行其它训练。

![image](https://github.com/WangRongsheng/CareLlama/assets/94682439/88b6a93a-787f-493b-9937-f3f6aeed131a)
这些数据集全都用到了吗？还是只是一部分？

**Comment by WangRongsheng** [comment]
只用到了一个。

**Comment by yuanzhiyong1999** [comment]
> 只用到了一个。

能告知是哪一个吗？

**Comment by WangRongsheng** [comment]
https://github.com/X-jun-0130/LLM-Pretrain-FineTune/tree/main/data_sft

**Comment by yuanzhiyong1999** [comment]
> https://github.com/X-jun-0130/LLM-Pretrain-FineTune/tree/main/data_sft

非常感谢您

**Comment by nibaba007** [comment]
执行：
accelerate launch src/train_bash.py \
    --stage sft \
    --model_name_or_path ./Llama-7b-hf \
    --do_train \ 。。。。。。
  报错Some of the datasets have disparate format. Resetting the format of the concatenated dataset.

![image](https://github.com/WangRongsheng/CareGPT/assets/101156432/3caab0e9-f880-480b-a71a-3a6f37c9eec1)
