### ISSUE TITLE
启动gradio报错

### ISSUE THREAD

**Issue by zhengorange** [WangRongsheng/CareGPT#6]
你好，为了快速体验一下微调后llama2的医疗问答效果，我从您提供的地址“wangrongsheng/CareLlama2-7b-multi“下载了模型，并将其放在CareGPT跟目录下，然后修改CareGPT/Gradio/model.py中的底7行model_id = '../CareLlama2-7b-multi'。然后按照文档安装完依赖，执行python app.py，报了下面的错，请问大佬，这大概是哪里出了问题？

OSError: Unable to load weights from pytorch checkpoint file for '../CareLlama2-7b-multi/pytorch_model-00001-of-00002.bin' at '../CareLlama2-7b-multi/pytorch_model-00001-of-00002.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by WangRongsheng** [comment]
请看https://github.com/huggingface/transformers/issues/4336
