### ISSUE TITLE
这么多数据训完干不过通用模型，想知道作者什么看法？

### ISSUE THREAD

**Issue by yucc-leon** [WangRongsheng/CareGPT#7]
我也在做行业模型微调（金融法律相关），也遇到了很多微调后效果不理想的问题（但通过牺牲通用能力换取少量的转有能力提升，但实际上不挂知识库还远远达不到应用预期）。lawbench的评测也有类似结论。
想知道作者对此有什么想法，有兴趣可以私聊交流一下哈哈

**Comment by nibaba007** [comment]
![image](https://github.com/WangRongsheng/CareGPT/assets/101156432/6c257ffc-9e2c-49d6-9a1f-be95b857c4d6)
在 '--dataset', 'mm,hm',中；在mm和hm中的multi-med.json、huatuo-med.json如何定义的。
 "hm": {
    "file_name": "huatuo-med.json",
    "columns": {
      "prompt": "instruction",
      "query": "",
      "response": "output",
      "history": ""
    }
  },
  "mm": {
    "file_name": "multi-med.json",
    "columns": {
      "prompt": "instruction",
      "query": "",
      "response": "output",
      "history": "history"
    }

**Comment by nibaba007** [comment]
报错： File "D:\code\CareGPT-main\src\llmtuner\dsets\loader.py", line 48, in get_dataset
    raise ValueError("File not found.")

**Comment by WangRongsheng** [comment]
> ![image](https://user-images.githubusercontent.com/101156432/283724463-6c257ffc-9e2c-49d6-9a1f-be95b857c4d6.png) 在 '--dataset', 'mm,hm',中；在mm和hm中的multi-med.json、huatuo-med.json如何定义的。 "hm": { "file_name": "huatuo-med.json", "columns": { "prompt": "instruction", "query": "", "response": "output", "history": "" } }, "mm": { "file_name": "multi-med.json", "columns": { "prompt": "instruction", "query": "", "response": "output", "history": "history" }

请参考：https://github.com/WangRongsheng/CareGPT/blob/main/data/self_cognition.json

**Comment by nibaba007** [comment]
参考：https://github.com/WangRongsheng/CareGPT/blob/main/data/self_cognition.json
写了multi-med.json、huatuo-med.json文件后，执行命令还是报错：
![image](https://github.com/WangRongsheng/CareGPT/assets/101156432/ce2e5689-8979-438b-83d9-5dee8b972c2e)

[INFO|tokenization_utils_base.py:2020] 2023-11-17 21:48:58,704 >> loading file tokenizer.model
[INFO|tokenization_utils_base.py:2020] 2023-11-17 21:48:58,704 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:2020] 2023-11-17 21:48:58,704 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:2020] 2023-11-17 21:48:58,704 >> loading file tokenizer_config.json
[INFO|tokenization_utils_base.py:2020] 2023-11-17 21:48:58,704 >> loading file tokenizer.json
Traceback (most recent call last):
  File "D:\code\CareGPT-main\src\train_bash.py", line 14, in <module>
    main()
  File "D:\code\CareGPT-main\src\train_bash.py", line 5, in main
    run_exp()
  File "D:\code\CareGPT-main\src\llmtuner\tuner\tune.py", line 26, in run_exp
    run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
  File "D:\code\CareGPT-main\src\llmtuner\tuner\sft\workflow.py", line 28, in run_sft
    model, tokenizer = load_model_and_tokenizer(model_args, finetuning_args, training_args.do_train, stage="sft")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\CareGPT-main\src\llmtuner\tuner\core\loader.py", line 76, in load_model_and_tokenizer
    config = AutoConfig.from_pretrained(model_to_load, **config_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Softdown\Anaconda\envs\llm\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1048, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Softdown\Anaconda\envs\llm\Lib\site-packages\transformers\configuration_utils.py", line 622, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Softdown\Anaconda\envs\llm\Lib\site-packages\transformers\configuration_utils.py", line 677, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "E:\Softdown\Anaconda\envs\llm\Lib\site-packages\transformers\utils\hub.py", line 401, in cached_file
    raise EnvironmentError(
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\Softdown\\Anaconda\\envs\\llm\\python.exe', 'src/train_bash.py', '--stage', 'sft', '--model_name_or_path',
 './llama_model/7B', '--do_train', '--dataset', 'mm,hm', '--finetuning_type', 'lora', '--overwrite_cache', '--output_dir', './output-1', '--per_device_t
rain_batch_size', '4', '--gradient_accumulation_steps', '4', '--lr_scheduler_type', 'cosine', '--logging_steps', '10', '--save_steps', '2000', '--learni
ng_rate', '5e-5', '--num_train_epochs', '2.0', '--plot_loss', '--template', 'default', '--lora_target', 'q_proj,v_proj']' returned non-zero exit status 
1.
