### ISSUE TITLE
Questions Regarding Instructions #8 and #10

### ISSUE THREAD

**Issue by HolmesShuan** [WangRongsheng/CareGPT#9]
想请教一下作者，关于实践经验的两个问题，还望不吝赐教：
1. 第八条中“对于垂类模型，或许我们更应该关注PT的过程，而不是采集千万百万的SFT数据做训练，我们的建议是大规模预训练+小规模监督微调=超强的LLM模型；”，请问这里的“大规模预训练”是指继承通用大语言模型参数还是在垂类上预训练呢？“小规模监督微调”如何解决通用语言模型无法理解垂域专有词汇或背景知识不足的问题呢（目前是 RAG，但感觉效果还不够好）？如果以医疗chatbot 为例，这里的“千万百万的SFT”指的是人工标记的问答么？
2. 第十条中“预训练可以灌入知识，监督微调只是激活领域能力(无法关注知识)？预训练的知识与监督微调知识应该呼应？预训练几十GB的语料知识会被原来数万亿token预训练的模型知识淹没？”请问这里的“预训练几十GB的语料知识”中的“预训练”实际指的是二次预训练么，即在专用知识库上自回归训练么？“原来数万亿token预训练的模型知识”中的“预训练”实际指的是通用语言模型的预训练么？目前确实观察到了“预训练可以灌入知识”，即全参数的二次预训练可以引入新知识，但是通用语言能力会有损失。请教一下作者，对于有监督微调的数据量、数据选择及训练方式（全参数/LoRA-family）有没有什么经验性的指导意见。

感谢！

---

I would like to consult the author on two questions about practical experience, and I hope you could kindly provide your insights:
1. In the eighth article, it is stated that "For vertical models, perhaps we should pay more attention to the PT process, rather than collecting tens of millions of SFT data for training, our suggestion is large-scale pre-training + small-scale supervised fine-tuning = super strong LLM model." Could you please clarify whether "large-scale pre-training" refers to inheriting the parameters of the general large language model or pre-training on the vertical field? How does "small-scale supervised fine-tuning" solve the problem of the general language model not understanding vertical-specific vocabulary or lacking background knowledge (currently it is RAG, but the effect seems not good enough)? If we take a medical chatbot as an example, does "tens of millions of SFT" refer to manually labeled Q&A?
2. In the tenth article, it is stated that "Pre-training can instill knowledge, and supervised fine-tuning only activates domain capabilities (cannot focus on knowledge)? Should the knowledge of pre-training and the knowledge of supervised fine-tuning correspond? Will the knowledge of tens of GB of pre-training corpus be overwhelmed by the knowledge of the original model pre-trained with trillions of tokens?" Could you please specify whether the "pre-training" in "pre-training tens of GB of corpus knowledge" actually refers to secondary pre-training, that is, autoregressive training on a dedicated knowledge base? Does the "pre-training" in "the original model pre-trained with trillions of tokens" actually refer to the pre-training of the general language model? At present, we indeed observe that "pre-training can instill knowledge", that is, full-parameter secondary pre-training can introduce new knowledge, but the general language ability will be lost. I would like to ask the author if there is any experiential guidance on the amount of data, data selection, and training methods (full parameters/LoRA-family) for supervised fine-tuning.
Thank you!

**Comment by WangRongsheng** [comment]
1. 这里的大规模预训练可以看作是增量预训练。“小规模监督微调”应该注重底座模型能力和监督微调数据的质量。这里的千万百万的SFT指的是任何方式收集来的数据（包括人工制作和其它方法）。
2. 是二次预训练。是指原来通用模型的预训练。通用能力的丧失是必然，看你场景下需要保持怎么样的能力，一般来说全参数微调比LoRA性能较好一点，但是可以主要以LoRA为主，数据以质量为主，数据量在万条以上。
